db.alumnos.find({Nombre: "Said"});
db.alumnos.find({Nombre: "Abril"});
db.alumnos.find({Nombre: "Paula"});
db.alumnos.find({Edad: "16"});
db.alumnos.find({Nombre: "Lucca"});
db.alumnos.find({Edad: "17"});
db.alumnos.find({Nombre: "Ferny"});
db.alumnos.find({Nombre: "Camila"});
db.alumnos.find({Edad: "19"});
db.alumnos.find({Edad: "18"});
db.profesores.find({Nombre: "Ana"});
db.profesores.find({Materia: "Historia"});
db.profesores.find({Materia: "Geografia"});
db.profesores.find({Nombre: "Patricia"});
db.profesores.find({Nombre: "David"});
db.profesores.find({Materia: "Fisica"});
db.profesores.find({Materia: "Español"});
db.profesores.find({Nombre: "Claudia"});
db.profesores.find({Nombre: "Jorge"});
db.profesores.find({Nombre: "Maria"});
db.edificios.find({Altura: "152"});
db.edificios.find({Altura: "285"});
db.edificios.find({Nombre: "Torre Aurora"});
db.edificios.find({Nombre: "Torre Esmeralda"});
db.edificios.find({Altura: "167"});
db.edificios.find({Altura: "240"});
db.edificios.find({Altura: "340"});
db.edificios.find({Nombre: "Torre Solaris"});
db.edificios.find({Nombre: "Residencial Altavista"});
db.edificios.find({Nombre: "Centro Empresarial Nexus"});
db.salones.find({Salon: "B"});
db.salones.find({Caracteristica: "Amplio"});
db.salones.find({Salon: "D"});
db.salones.find({Salon: "H"});
db.salones.find({Caracteristica: "Enchufes múltiples"});
db.salones.find({Caracteristica: "Mobiliario nuevo"});
db.salones.find({Salon: "E"});
db.salones.find({Salon: "J"});
db.salones.find({Caracteristica: "Piso antiderrapante"});
db.salones.find({Salon: "G"});
db.materias.find({Materia: "Matemáticas"});
db.materias.find({Caracteristica: "Mapas físicos"});
db.materias.find({Caracteristica: "Dibujo básico"});
db.materias.find({Materia: "Artes"});
db.materias.find({Materia: "Educación Física"});
db.materias.find({Materia: "Historia"});
db.materias.find({Caracteristica: "Valores éticos"});
db.materias.find({Caracteristica: "Coordinación motriz"});
db.materias.find({Materia: "Formación Cívica"});
db.materias.find({Materia: "Español"});